"use client";

import { ReactNode } from "react";
import { cn } from "@/lib/utils";
import { formatCurrency, formatDate } from "@/lib/utils";

export type ReportKpi = {
  label: string;
  value: string | number;
  sublabel?: string;
  accent?: "emerald" | "gold" | "neutral" | "danger";
};

export type ReportSettingsInfo = {
  businessName: string;
  businessAddress?: string | null;
  phone?: string | null;
  email?: string | null;
};

type ReportViewerProps = {
  title: string;
  subtitle?: string;
  settings: ReportSettingsInfo;
  dateRangeLabel: string;
  generatedBy?: string | null;
  generatedAt: Date;
  kpis?: ReportKpi[];
  children?: ReactNode;
  footerNote?: string;
  empty?: boolean;
  emptyMessage?: string;
  className?: string;
};

const KPI_ACCENT: Record<NonNullable<ReportKpi["accent"]>, string> = {
  emerald: "border-emerald-500/40 bg-emerald-50 text-emerald-900",
  gold: "border-amber-500/40 bg-amber-50 text-amber-950",
  neutral: "border-slate-200 bg-slate-50 text-slate-900",
  danger: "border-red-300/60 bg-red-50 text-red-900",
};

export function ReportViewer({
  title,
  subtitle,
  settings,
  dateRangeLabel,
  generatedBy,
  generatedAt,
  kpis = [],
  children,
  footerNote,
  empty = false,
  emptyMessage = "No records found for this date range.",
  className,
}: ReportViewerProps) {
  return (
    <article
      id="report-print-area"
      className={cn(
        "report-canvas rounded-xl border border-slate-200 bg-white text-slate-900 shadow-lg shadow-black/5",
        className
      )}
    >
      <header className="border-b border-slate-200 px-6 py-5 print:px-4 print:py-4">
        <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
          <div>
            <p className="text-xs font-semibold uppercase tracking-widest text-emerald-700">
              RAGEN RESORT POS
            </p>
            <h2 className="mt-1 font-serif text-2xl font-bold text-slate-900">{title}</h2>
            {subtitle && <p className="mt-1 text-sm text-slate-600">{subtitle}</p>}
          </div>
          <div className="text-right text-sm text-slate-600">
            <p className="font-semibold text-slate-900">{settings.businessName}</p>
            {settings.businessAddress && <p>{settings.businessAddress}</p>}
            {(settings.phone || settings.email) && (
              <p>
                {[settings.phone, settings.email].filter(Boolean).join(" • ")}
              </p>
            )}
          </div>
        </div>
        <div className="mt-4 flex flex-wrap gap-x-6 gap-y-1 border-t border-slate-100 pt-4 text-xs text-slate-500">
          <span>
            <strong className="text-slate-700">Period:</strong> {dateRangeLabel}
          </span>
          {generatedBy && (
            <span>
              <strong className="text-slate-700">Generated by:</strong> {generatedBy}
            </span>
          )}
          <span>
            <strong className="text-slate-700">Generated at:</strong>{" "}
            {formatDate(generatedAt)}
          </span>
        </div>
      </header>

      {kpis.length > 0 && (
        <section className="grid gap-3 border-b border-slate-100 px-6 py-4 sm:grid-cols-2 lg:grid-cols-4 print:grid-cols-4">
          {kpis.map((kpi) => (
            <div
              key={kpi.label}
              className={cn(
                "rounded-lg border px-4 py-3",
                KPI_ACCENT[kpi.accent ?? "neutral"]
              )}
            >
              <p className="text-xs font-medium uppercase tracking-wide opacity-80">
                {kpi.label}
              </p>
              <p className="mt-1 text-xl font-bold tabular-nums">
                {typeof kpi.value === "number" ? formatCurrency(kpi.value) : kpi.value}
              </p>
              {kpi.sublabel && <p className="mt-0.5 text-xs opacity-75">{kpi.sublabel}</p>}
            </div>
          ))}
        </section>
      )}

      <div className="px-6 py-5 print:px-4">
        {empty ? (
          <div className="flex min-h-[200px] flex-col items-center justify-center rounded-lg border border-dashed border-slate-200 bg-slate-50/80 py-16 text-center">
            <p className="font-medium text-slate-700">{emptyMessage}</p>
            <p className="mt-2 max-w-md text-sm text-slate-500">
              Adjust the date range or generate again when new transactions are recorded.
            </p>
          </div>
        ) : (
          children
        )}
      </div>

      <footer className="border-t border-slate-200 px-6 py-3 text-center text-xs text-slate-500 print:px-4">
        {footerNote ?? `© ${new Date().getFullYear()} ${settings.businessName} — Confidential business report`}
      </footer>
    </article>
  );
}

export function ReportSection({
  title,
  children,
  className,
}: {
  title: string;
  children: ReactNode;
  className?: string;
}) {
  return (
    <section className={cn("mb-8 last:mb-0", className)}>
      <h3 className="mb-3 border-l-4 border-emerald-600 pl-3 font-serif text-lg font-semibold text-slate-800">
        {title}
      </h3>
      {children}
    </section>
  );
}

export function ReportTable({
  columns,
  rows,
  emptyLabel = "No rows",
}: {
  columns: string[];
  rows: (string | number)[][];
  emptyLabel?: string;
}) {
  if (rows.length === 0) {
    return <p className="text-sm text-slate-500">{emptyLabel}</p>;
  }

  return (
    <div className="report-table-scroll overflow-x-auto rounded-lg border border-slate-200">
      <table className="w-full min-w-[480px] border-collapse text-left text-sm">
        <thead>
          <tr className="bg-slate-50 text-xs uppercase tracking-wide text-slate-600">
            {columns.map((col) => (
              <th key={col} className="whitespace-nowrap border-b border-slate-200 px-4 py-2.5 font-semibold">
                {col}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {rows.map((row, i) => (
            <tr key={i} className="border-b border-slate-100 even:bg-slate-50/50">
              {row.map((cell, j) => (
                <td key={j} className="whitespace-nowrap px-4 py-2.5 text-slate-800">
                  {cell}
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

export function printReport() {
  window.print();
}
